### ISSUE TITLE
Ncat invalid option -q

### ISSUE THREAD

**Issue by xaetacore** [JackV2020/Root-A-Toon-USB-Stick#1]
The root and activation script crashed because the latest version of ncat doesn't seem to support the -q option anymore.

**Comment by JackV2020** [comment]
I updated the download instruction to find older versions of the live iso and an indication of which one I think I used and hope this helps.
Could you let me know if this helps and when you are successful please let me know which version you downloaded.
Success, good luck and many thanks in advance.

**Comment by xaetacore** [comment]
Thanks I'll give this another try based on the version you have used.

For now i used the temp subscription method to activate the toon 1 now I'll cross my finger for a successful rooting process :)

**Comment by xaetacore** [comment]
I can confirm that indeed 2021.4 works for people with the ncat incompatibility issue on the latest kali version.

I downloaded 2021.4 and it worked without any issues.

I found another little mistake in the readme.md

The links you provided don't work as old.kali.org don't support https anymore.

Changing them to http://old.kali.org will fix that issue aswell👍

**Comment by JackV2020** [comment]
Oke, thanks for the feedback.
I just updated the README.md so it shows a better way to get the Kali version and what version I have on my USB stick which is version 2021.2
Glad it worked for you 🙂
