### ISSUE TITLE
Wifi dont work

### ISSUE THREAD

**Issue by mjs1987** [JackV2020/Root-A-Toon-USB-Stick#3]
When i boot kali,

On my pc,

Ik cant see the WiFi in toon,

I ussed an WiFi usb stick

**Comment by JackV2020** [comment]
I have no experience with USB WiFi sticks but will try to help you.
The script setup-wifi.sh expects a wlan0 interface.
Please boot Kali and start a terminal.
(In the top left corner of Kali is a black box and a $ sign in it.)
Type the command ifconfig in the terminal window.
Do you see a wlan0 interface ?
If so you should be able to run ./setup-wifi.sh and a WiFi SSID ToonRouter should be created.
Can you verify with your smart phone if this SSID exists ?
If not maybe the WiFi stick is not supported or maybe you have to plug it in before or very shortly after booting the Kali stick and try again.

**Comment by mjs1987** [comment]
![16594455319607414988244424189573](https://user-images.githubusercontent.com/16963991/182381841-c610bf32-b1b5-4034-bb65-b0e9fdd629b1.jpg)
![16594455530547132866553319050718](https://user-images.githubusercontent.com/16963991/182381889-072e459e-259b-41a1-87aa-2f681ab046cc.jpg)


But dont see the ssid

**Comment by mjs1987** [comment]
I have tried with an laptop, got the same nee ssid

**Comment by JackV2020** [comment]
Oke, I see you have a wlan0: interface and I am not sure how I can help you.
Maybe we can do the next 2 things to get an idea.
1 is to check if your stick is supported by Kali
2 is to try to setup the shared WiFi by hand.

1) Lets try to check if your WiFi stick works in Kali.
We try to get the WiFi of the computer connected to your own WiFi so you can browse the Internet. 
Unplug the Ethernet cable so when we get an Internet connection we know we go via WiFi.
Boot Kali with your WiFi stick so you get a wlan0 interface.
In the upper right corner next to the clock is a little square.
Right click that and select Edit Connections
Click the big + and in the drop down box where it says Ethernet you select WiFi
Click Create and you end up on a 2nd tab of a setup tool.
In the SSID box you type the SSID you want to connect to
I think the 3rd option from the bottom is device and this is where you select wlan0:
Go to the 3rd Tab on WiFi Security.
For WiFi security you select WPA&WPA2 Personal
You get an extra field in which you enter the password of your WiFi.
Click Save at the bottom and your computer should connect to your WiFi.
In the left upper corner is a little globe with which you can start a web browser.
Try to browse to a website like www.google.com
When this works your WiFi stick seems to be supported.

2) When the above works try to setup the access point by hand.
Reboot Kali to start with clean settings.
start the web browser with the little globe icon and start a terminal window with the black square with a $ in it.
in the url box type : github jackv2020
and press enter. You will find my github and you can browse to Root-A-Toon-USB-Stick.
Click on setup-wifi.sh
copy row 38:

nmcli connection add type wifi ifname wlan0 con-name ToonRouter autoconnect yes  ssid ToonRouter mode ap 802-11-wireless.mode ap ipv4.method shared

Right click in the terminal window and select paste clipboard
Press enter
Now you should be able to connect your phone and Toon to the SSID ToonRouter without entering a password.
2 screenshots below. First what my Kali screen looks like and second what my phone shows.

I hope this helps.

![20220802_203357](https://user-images.githubusercontent.com/71119057/182451516-40282e29-8fd9-4022-98cc-713c4ebece55.jpg)

![Screenshot_20220802-203325_Settings](https://user-images.githubusercontent.com/71119057/182453620-e04c1afa-4ff4-49ba-aa1a-4c57ce3deb92.jpg)

**Comment by mjs1987** [comment]
![16595147008717342001901079461628](https://user-images.githubusercontent.com/16963991/182559655-055f7f61-4f8d-41de-ade7-30d1113c496e.jpg)
![Screenshot_20220803-101847_Settings](https://user-images.githubusercontent.com/16963991/182559736-27198ad5-9a9d-4669-9bc9-84a13768924c.jpg)

Verry strange,

**Comment by JackV2020** [comment]
I guess you were able to browse to the Internet with step 1.
Now it seems that the command did create the access point but you do not see it on your phone. 
Note that it may take some time for the SSID to appear on your phone. 
I have to stop the WiFi on my phone, wait 10-20 seconds, turn it on and wait for it to appear. 
Sometimes I do the disabling and enabling 3 times before I see it.

**Comment by mjs1987** [comment]
Yes, its there!

**Comment by JackV2020** [comment]
Glad it turns out to be fine.
I updated the README.md to ask for some patience.
'Patience is a virtue' 😉
