### ISSUE TITLE
No ToonRouter SSID visible

### ISSUE THREAD

**Issue by evanloon** [JackV2020/Root-A-Toon-USB-Stick#4]
Hi Jack,

I have tried the setup-wifi script on four different laptops, all with a built-in WiFi adapter (wlan0, verified) and booted from a Kali Live USB stick. Although the script seems to be working and a _nmcli con show_ does show both the network the laptop itself is connected to and the ToonRouter connection, the SSID is not visible. Not after stopping/starting WiFi on my phone and also not after waiting for more than an hour... Any idea what I can do to debug this issue?
Thanks in advance for your help!

Kind regards,
Eric

**Comment by JackV2020** [comment]
Hi Eric,

When you stop the wifi on your phone maybe wait 10-20 seconds before turning wifi on your phone back on again and then wait for the SSID ToonRouter to  appear. You may need to try a couple of times.
I am not a wifi expert but also find this very annoying.

Kind regards 

Jack 


⁣BlueMail voor Android downloaden ​

Op 31 aug. 2022 17:03, om 17:03, evanloon ***@***.***> schreef:

**Comment by evanloon** [comment]
Hi Jack,

I did some extensive investigation and the issue is that the majority of the WiFi adapters do not support WiFi sharing over the same adapter. So that's why it's not working on none of my laptops. However, there is a work-around: I I use the Ethernet connection of my laptop and enter the command _nmcli dev wifi hotspot ifname <Ethernet interface name> ssid Toonrooter password "<password>"_ you can create a WiFi hotspot which uses your Ethernet cable. I tested your script and everything is working too with a hotspot.
So maybe it's an idea to adapt your setup-wifi.sh script and embed this option in it? After startup, let the user choose which method he prefers and either start the _nmcli connection add_ option or the _nmcli dev wifi hotspot_ option.
Thanks for your help!

Kind regards,
Eric

**Comment by JackV2020** [comment]
Hi Eric,

maybe you could read the documentation on the page of the repository which tries to explain that you need a wired connection and WiFi. It does not say that both Internet access and Access point are on the same WiFi adapter. They are seperate.

The last sentence in the first part clearly states : 
" I created the script setup_wifi.sh to simplify the sharing of the wired Internet connection of your computer over the Wi-Fi to your Toon." 
From this you should understand that you need a wired connection to the Internet and a wifi connection.

The first sentence of the second section says that you need : 
"A 4 GB memory stick and a Windows/Linux/macOS/OS X computer with an Ethernet card and wifi."

Glad that it finally works by the way.

Kind regards,
Jack

**Comment by evanloon** [comment]
Hi Jack,

Indeed, you're absolutely right. I didn't read the instructions properly. My apologies.

Kind regards,
Eric

**Comment by JackV2020** [comment]
Never happens to me😇😇

I am glad it works now. 

By the way.....The repository is now in transition phase. I am handing it over to the github ToonSoftwareCollective so it can be maintained there.

Kind regards 

Jack 

⁣BlueMail voor Android downloaden ​

Op 29 sep. 2022 09:45, om 09:45, evanloon ***@***.***> schreef:
>Hi Jack,
>
>Indeed, you're absolutely right. I didn't read the instructions
>properly. My apologies.
>
>Kind regards,
>Eric
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/JackV2020/Root-A-Toon-USB-Stick/issues/4#issuecomment-1261894654
>You are receiving this because you modified the open/close state.
>
>Message ID:
***@***.***>
